# Generated by Django 2.2 on 2019-05-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiscussionBoard', '0003_auto_20190509_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
