# Generated by Django 2.2 on 2019-05-09 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DiscussionBoard', '0005_post_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='descreption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='DiscussionBoard.Topic'),
        ),
    ]
