# Generated by Django 2.2 on 2019-05-15 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DiscussionBoard', '0006_auto_20190509_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='DiscussionBoard.Topic'),
        ),
    ]
